#!/bin/bash
sudo su
cd /opt
wget http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz
tar -xvzf /opt/apache-tomcat-8.5.51.tar.gz
chmod +x /opt/apache-tomcat-8.5.51/bin/startup.sh shutdown.sh
ln -s /opt/apache-tomcat-8.5.51/bin/startup.sh /usr/bin/tomcatup
ln -s /opt/apache-tomcat-8.5.51/bin/shutdown.sh /usr/bin/tomcatdown
tomcatup
